services:
  db:
    image: postgres
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

# docker run --rm --name docker-postgres -e POSTGRES_PASSWORD=password -d -p 5432:5432 -v $PWD/db:/var/lib/postgresql/data postgres
# docker exec -it docker-postgres bash
# psql -h localhost -U postgres -d postgres